bot:
  api_path: https://api.telegram.org/bot
  token: 5629490839:AAG4EXFBeD1qevL8aIBuk0-vnxFmjh61yq4 
  id:
rabbitmq:
  queue_name:  tg_bot
  exchange_name: bot_exchange
  rabbit_url: amqp://rmuser:rmpassword@localhost:5672/